config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'articles#index'
  post   '/like/:article_id' => 'likes#like',   as: 'like'
  delete '/like/:article_id' => 'likes#unlike', as: 'unlike'
  post   '/join/:group_id' => 'groups#join', as: 'join'
  delete   '/exit/:group_id' => 'groups#exit', as: 'exit'

  resources :users,         only:[:index, :show]

  resources :groups,        only:[:new, :create, :index, :destroy, :update, :show, :edit] do
    resources :messages,    only:[:index, :create]
  end

  resources :gametitles,    only:[:index, :search] do
    collection do
      get :search
    end
  end

  resources :articles do
    resources :comments,      only:[:create] 
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :article_gametitles,dependent: :destroy
  has_many :gametitles, through: :article_gametitles
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  mount_uploader :image, ArticleThumbnailsUploader
  is_impressionable counter_cache: true
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_gametitles
  impressionist :actions=> [:show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = params[:gametitle_id].present? ? Gametitle.find(params[:gametitle_id]).articles.order(created_at: :DESC).page(params[:page]).per(8) : Article.order(created_at: :DESC).page(params[:page]).per(8)
    @result = params[:gametitle_id].present? ? Gametitle.find(params[:gametitle_id]) : ""
    @rank = params[:gametitle_id].present? ? Gametitle.find(params[:gametitle_id]).articles.order(impressions_count: :desc).take(5) : Article.order(impressions_count: :desc).take(5)
    @recommends = current_user.gametitles
    @populars = Gametitle.order(user_gametitle_count: :desc).take(6)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
    @like = Like.new
    impressionist(@article, nil, unique: [:session_hash])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :image, gametitle_ids: []).merge(user_id: current_user.id)
    end

    def set_gametitles
      @gametitles = Gametitle.all
    end
    
end

app/views/articles/_articles.html.haml
.articles
  - @articles.each do |article|
    = link_to article_path(article.id), method: :get do
      .articles__article.shadow.p-3.mb-5.rounded
        .articles__article--uper
          .title
            = article.title
          = render partial: 'shared/user', locals: { user: article.user, user_id: article.user.id}    
        .articles__article--thumbnail
          = image_tag article.image.url
= paginate @articles

app/views/articles/_form.html.haml
= form_with(model: article, local: true) do |form|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - article.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :content
    = form.text_area :content
  .field
    = form.label :image
    = form.file_field :image
  .field
    = form.collection_check_boxes :gametitle_ids, Gametitle.all, :id, :name
    -# - @gametitles.each do |gametitle|
      -# = form.check_box :gametitle_ids,
      -#   { multiple: true,checked: @article.gametitle.present? ? @article.gametitle.split(",").include?(gametitle) : false},gametitle, nil
      -# %span
      -#   = tag
    -# = form.collection_select :gametitle_ids, Gametitle.all, :id, :name
  .actions
    = form.submit

app/views/articles/_like.html.haml
.like-link{id: "like-link-#{@article.id}"}
  - if current_user.already_liked?(@article)
    = link_to unlike_path(@article.id), method: :delete, remote: true do
      = fa_icon 'thumbs-up', class: "thumbs-up-cancel"
  - else
    = link_to like_path(@article.id), method: :post, remote: true do
      = fa_icon 'thumbs-up', class: "thumbs-up"
  いいね数
  = @article.likes.length

app/views/articles/_populars.html.haml
.tags_popular
  .text.text-success
    人気のタイトル
  - @populars.each do |tag|
    = link_to articles_path(gametitle_id: tag), method: :get do
      %button.btn.btn-outline-secondary
        = fa_icon 'gamepad'
        = tag.name

app/views/articles/_ranking.html.haml
.ranking
  .text.text-success
    - if @result.present?
      = "#{@result.name}の人気記事"
    - else
      人気の記事
  - @rank.each_with_index do |rank, i|
    .title{class: "rank-#{i+1}"}
      - if (i < 3)
        = fa_icon 'circle', class: "circle-#{i+1}"
      = link_to article_path(rank), method: :get do
        = (i + 1)
        = rank.title

app/views/articles/_recommends.html.haml
- if @recommends.present? 
  .tag_recommend 
    .text.text-success
      あなたへのおすすめ
    - @recommends.each do |tag|
      = link_to articles_path(gametitle_id: tag), method: :get do
        %button.btn.btn-outline-secondary
          = fa_icon 'gamepad'
          = tag.name

app/views/articles/edit.html.haml
%h1 Editing Article
= render 'form', article: @article
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= render 'shared/header'
%main.article_index
  = render 'articles'    
.right
  .right__contents.shadow.p-3.mb-5.rounded
    .tag_search
      %input#gametitle-search-field{:placeholder => "タイトルを検索", :type => "text"}/
      %ul#gametitle-search-results
      - if @result.present?    
        = "#{@result.name}タグで検索"
    
    = render 'recommends'
    = render 'populars'        
    = render 'ranking'

app/views/articles/new.html.haml
= render 'shared/header'
%main
  %h1 New Article
  = render 'form', article: @article
  = link_to 'Back', articles_path

app/views/articles/show.html.haml
= render 'shared/header'
%main
  .article.shadow.p-3.mb-5.rounded
    .article__uper
      .title
        = @article.title
      = render partial: 'shared/user', locals: { user: @article.user, user_id: @article.user.id}          
    .article__main
      = @article.content
    .article__lower
      = render partial: 'shared/tags', locals: { hoge: @article }
      = render 'like'
      .delete
        pv数:
        = @article.impressionist_count
        - if @article.user.id == current_user.id         
          = link_to "/articles/#{@article.id}", method: :delete do
            = fa_icon 'trash'
          |
          = link_to 'Edit', edit_article_path(@article)
          |
        = link_to 'Back', articles_path              

  .comments
    - @comments.each do |c|
      = c.user.name
      = c.text
    = form_for [@article, @comment] do |f|
      = f.text_area :text
      = f.submit 
      
      
    