config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'articles#index'
  post   '/like/:article_id' => 'likes#like',   as: 'like'
  delete '/like/:article_id' => 'likes#unlike', as: 'unlike'
  post   '/join/:group_id' => 'groups#join', as: 'join'
  delete   '/exit/:group_id' => 'groups#exit', as: 'exit'

  resources :users,         only:[:index, :show]

  resources :groups,        only:[:new, :create, :index, :destroy, :update, :show, :edit] do
    resources :messages,    only:[:index, :create]
  end

  resources :gametitles,    only:[:index, :search] do
    collection do
      get :search
    end
  end

  resources :articles do
    resources :comments,      only:[:create] 
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages

  has_many :group_gametitles, dependent: :destroy
  has_many :gametitles, through: :group_gametitles

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  mount_uploader :image, GroupImageUploader

  def join?(user_id)
    self.user_ids.include?(user_id)
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:join, :exit]

  # GET /groups
  # GET /groups.json
  def index
    @groups = params[:gametitle_id].present? ? Gametitle.find(params[:gametitle_id]).groups.order(created_at: :DESC) : current_user.groups.order(created_at: :DESC)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # binding.pry
    @group = Group.find(params[:id])
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.users << current_user
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
    # respond_to do |format|
    #   if @group.save
    #     format.html { redirect_to @group, notice: 'Group was successfully created.' }
    #     format.json { render :show, status: :created, location: @group }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @group.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    if current_user.id == @group.leader_id
      if @group.update(group_params)
        redirect_to group_messages_path(@group)
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def join
    group_users = current_user.group_users.new(group_id: @group.id)
    group_users.save
    redirect_to group_messages_path(@group)
  end

  def exit
    group_users = current_user.group_users.find_by(group_id: @group.id)
    group_users.destroy
    redirect_to group_messages_path(@group)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:title, :image, :memo, user_ids: [], gametitle_ids: []).merge(leader_id: current_user.id)
    end

    def group_join
      params.require(:group).permit(user_ids: [])
    end
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |message|
          %li= message
  .field
    = f.text_area :title, placeholder: 'グループ名を入力してください'
  .field
    = f.collection_check_boxes :user_ids, User.all, :id, :name
  .field
    = f.collection_check_boxes :gametitle_ids, Gametitle.all, :id, :name
  .field
    = f.file_field :image
  .field
    = f.text_area :memo, placeholder: 'グループのメモ'
  .actions
    = f.submit 'Save'

app/views/groups/_memo.html.haml
.memo
  = "#{@group.title}のグループメモ"
  = @group.memo
- if current_user.id == @group.leader_id
  
  = link_to edit_group_path(@group.id), method: :get do
    %button.btn.btn-success{type: "button"}
      グループを編集する
- if @group.join?(current_user.id)
  = link_to exit_path(@group.id), method: :delete do
    %button.btn.btn-danger{type: "button"}
      グループを抜ける

app/views/groups/edit.html.haml
= form_for @group do |f|
  .field
    = f.text_area :title, placeholder: 'グループ名を入力してください'
  .field
    = f.file_field :image
  .field
    = f.text_area :memo, placeholder: 'グループのメモ'
  .actions
    = f.submit 'Save'

app/views/groups/index.html.haml
= render 'shared/header'
%main
  = link_to new_group_path do
    .create-group
      %button.btn.bg-white.btn-lg.btn-block.border{tyoe: "button"}
        = fa_icon 'plus'
        グループを作る
  .tag_search
    %input#group-search-field{:placeholder => "グループを検索", :type => "text"}/
    %ul#gametitle-search-results
    - if @result.present?    
      = "#{@result.name}タグで検索"

  .groups
    - @groups.each do |group|
      = link_to group_messages_path(group.id) do
        .groups__group.shadow.mb-5.rounded
          .groups__group--uper
            .group-image
              = image_tag group.image.url
            .info
              .title
                = group.title
              .user-length
                = fa_icon 'user'
                = "#{group.users.length}人"
                |
                = group.created_at.strftime("%Y/%m/%d %H:%M")

          .groups__group--lower
            - if group.messages.present? 
              .message
                = group.messages.last.content
            - else
              メッセージが投稿されていません
                  

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.js.erb
$("#messages-memo").html('<%= escape_javascript(render "memo") %>');
  var messages = document.getElementById( "group-header-low__left" );
  var memo = document.getElementById("group-header-low__right");

  if (!$( "#group-header-low__right" ).children().hasClass('active')){
    memo.classList.add("active");
    messages.classList.remove("active");
  } 
  
console.log('ok');