config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'articles#index'
  post   '/like/:article_id' => 'likes#like',   as: 'like'
  delete '/like/:article_id' => 'likes#unlike', as: 'unlike'
  post   '/join/:group_id' => 'groups#join', as: 'join'
  delete   '/exit/:group_id' => 'groups#exit', as: 'exit'

  resources :users,         only:[:index, :show]

  resources :groups,        only:[:new, :create, :index, :destroy, :update, :show, :edit] do
    resources :messages,    only:[:index, :create]
  end

  resources :gametitles,    only:[:index, :search] do
    collection do
      get :search
    end
  end

  resources :articles do
    resources :comments,      only:[:create] 
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_follow.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー中', class: 'follow-now btn btn-success'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー', class: 'follows btn btn-outline-success'
  

app/views/shared/_header.html.haml
.header.container
  .row 
    %button.article.btn.btn-dark.col-sm
      = link_to articles_path, method: :get do
        BLOG
        = fa_icon 'book', class: 'icon'
    %button.mypage.btn.btn-dark.col-sm
      = link_to user_path(current_user.id), method: :get, class: "mypage" do
        My Page
    %button.group.btn.btn-dark.col-sm
      = link_to groups_path, method: :get, class: "group" do
        GROUP
    %button.logout.btn.btn-dark.col-sm{type: "button"}
      = link_to destroy_user_session_path, method: :delete, class: "logout" do
        logout

app/views/shared/_tags.html.haml
%ul.tags
  - hoge.gametitles.each do |g|
    %li.tags__tag.shadow.p-3.mb-5.rounded
      = fa_icon 'tag', class: "tags__tag--icon"
      = g.name

app/views/shared/_user.html.haml
.user_info
  = link_to user_path(user_id) do
    = image_tag user.image.url, class: "rounded-circle"
  .user_info__user_name
    = user.name